export const FILETYPE_TEXT = ".txt"
export const FILETYPE_PDF = ".pdf"
export const FILETYPE_SHORTCUT = ".lnk"
export const FILETYPE_EXECUTABLE = ".exe"
export const FILETYPE_URL_SHORTCUT = ".url"

export const FILETYPE_URL_SHORTCUT_PROPERTY = "url"
export const FILETYPE_RENDERABLE_PROPERTY = "render"
export const BRANCHING_CONTEXT_PARENT_PROPERTY = "parent"
export const BRANCHING_CONTEXT_DETERMINER = "branches"
export const BRANCHING_EXECUTABLE_DETERMINER = "getBranchingContext"
export const SHORTCUT_DETERMINER = "context"
export const BRANCHING_CONTEXT_TYPE_PROPERTY = "type"
export const LEAF_EXTENSION_PROPERTY_NAME = "extension"
export const DEFAULT_POINTER = "default"
export const DEFAULT_TASKBAR_HEIGHT_PIXELS = 48
export const DEFAULT_MIN_WINDOW_HEIGHT_PIXELS = 150
export const DEFAULT_MIN_WINDOW_WIDTH_PIXELS = 200
export const TASKBAR_ITEM_CLASS = "taskbar-item"
export const TASKBAR_ITEM_NAME_CLASS = "taskbar-item__name"
export const DESKTOP_ITEM_CLASS = "desktop-item"
export const DESKTOP_ITEM_ICON_CLASS = "desktop-item__icon"
export const DESKTOP_ITEM_NAME_CLASS = "desktop-item__name"
export const NO_SELECT_CLASS = "no-select"
export const DATE_DISPLAY_BASE_CLASS = "date-display"
export const DATE_DISPLAY_OVERLAY_CLASS = "date-display__overlay"
export const DATE_DISPLAY_PICKER_ID = "date-display__input"

export const DEFAULT_DOCUMENT_TITLE = "Oliver Bathurst"
export const DEFAULT_FAVICON_HREF = "/favicon.ico?v=2"