name: NPM Build and Artifact Upload

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 25.x
        check-latest: true

    - name: NPM I And Build
      run: |
        npm install
        npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: github-pages
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist/

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
